name: Leaked Secrets Scan

# Currently only support this on PRs
on: [pull_request]

jobs:
  # Name of the First Job
  secrets-scanner-trufflehog-high-signal:

    runs-on: ubuntu-latest

    steps:
      # Checks out the code into the space
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # pulls TruffleHogs supported Docker image and runs
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD